apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todos-secret     # Name of secret containing the root password
                  key: root-password    # Key of secret for the root password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: todos-configmap  # Name of the ConfigMap containing the database name
                  key: database          # Key within the ConfigMap for the database name
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql  # Mount path for the persistent storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim   # Name of the PersistentVolumeClaim for persistent storage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
